site_name: GH-Go

repo_name: rajatgoel/gh-go
repo_url: https://github.com/rajatgoel/gh-go
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - toc.follow

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - blog
  - search

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting started:
    - Installation: installation.md
    - Running:
      - Single node: single_node.md
    - Troubleshooting: troubleshooting.md
  - Architecture:
    - architecture.md
    - Core concepts: concepts.md
    - Dependencies: dependencies.md
  - Developers:
    - Configuration: configuration.md
  - Development log:
    - blog/index.md
