// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: frontend/v1/service.proto

package v1

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   int64                  `protobuf:"varint,1,opt,name=key"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_frontend_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PutRequest) GetKey() int64 {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return 0
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *PutRequest) SetKey(v int64) {
	x.xxx_hidden_Key = v
}

func (x *PutRequest) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type PutRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   int64
	Value string
}

func (b0 PutRequest_builder) Build() *PutRequest {
	m0 := &PutRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_frontend_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PutResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PutResponse_builder) Build() *PutResponse {
	m0 := &PutResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key int64                  `protobuf:"varint,1,opt,name=key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_frontend_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetKey() int64 {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return 0
}

func (x *GetRequest) SetKey(v int64) {
	x.xxx_hidden_Key = v
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key int64
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	return m0
}

type GetResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value string                 `protobuf:"bytes,1,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_frontend_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *GetResponse) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type GetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value string
}

func (b0 GetResponse_builder) Build() *GetResponse {
	m0 := &GetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

var File_frontend_v1_service_proto protoreflect.FileDescriptor

const file_frontend_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19frontend/v1/service.proto\x12\vfrontend.v1\"B\n" +
	"\n" +
	"PutRequest\x12\x17\n" +
	"\x03key\x18\x01 \x01(\x03B\x05\xaa\x01\x02\b\x02R\x03key\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05value\"\r\n" +
	"\vPutResponse\"%\n" +
	"\n" +
	"GetRequest\x12\x17\n" +
	"\x03key\x18\x01 \x01(\x03B\x05\xaa\x01\x02\b\x02R\x03key\"*\n" +
	"\vGetResponse\x12\x1b\n" +
	"\x05value\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05value2\x85\x01\n" +
	"\x0fFrontendService\x128\n" +
	"\x03Put\x12\x17.frontend.v1.PutRequest\x1a\x18.frontend.v1.PutResponse\x128\n" +
	"\x03Get\x12\x17.frontend.v1.GetRequest\x1a\x18.frontend.v1.GetResponseB.Z,github.com/rajatgoel/gh-go/proto/frontend/v1b\beditionsp\xe8\a"

var file_frontend_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_frontend_v1_service_proto_goTypes = []any{
	(*PutRequest)(nil),  // 0: frontend.v1.PutRequest
	(*PutResponse)(nil), // 1: frontend.v1.PutResponse
	(*GetRequest)(nil),  // 2: frontend.v1.GetRequest
	(*GetResponse)(nil), // 3: frontend.v1.GetResponse
}
var file_frontend_v1_service_proto_depIdxs = []int32{
	0, // 0: frontend.v1.FrontendService.Put:input_type -> frontend.v1.PutRequest
	2, // 1: frontend.v1.FrontendService.Get:input_type -> frontend.v1.GetRequest
	1, // 2: frontend.v1.FrontendService.Put:output_type -> frontend.v1.PutResponse
	3, // 3: frontend.v1.FrontendService.Get:output_type -> frontend.v1.GetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frontend_v1_service_proto_init() }
func file_frontend_v1_service_proto_init() {
	if File_frontend_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontend_v1_service_proto_rawDesc), len(file_frontend_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontend_v1_service_proto_goTypes,
		DependencyIndexes: file_frontend_v1_service_proto_depIdxs,
		MessageInfos:      file_frontend_v1_service_proto_msgTypes,
	}.Build()
	File_frontend_v1_service_proto = out.File
	file_frontend_v1_service_proto_goTypes = nil
	file_frontend_v1_service_proto_depIdxs = nil
}
