// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: frontend/v1/service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/rajatgoel/gh-go/proto/frontend/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FrontendServiceName is the fully-qualified name of the FrontendService service.
	FrontendServiceName = "frontend.v1.FrontendService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FrontendServicePutProcedure is the fully-qualified name of the FrontendService's Put RPC.
	FrontendServicePutProcedure = "/frontend.v1.FrontendService/Put"
	// FrontendServiceGetProcedure is the fully-qualified name of the FrontendService's Get RPC.
	FrontendServiceGetProcedure = "/frontend.v1.FrontendService/Get"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	frontendServiceServiceDescriptor   = v1.File_frontend_v1_service_proto.Services().ByName("FrontendService")
	frontendServicePutMethodDescriptor = frontendServiceServiceDescriptor.Methods().ByName("Put")
	frontendServiceGetMethodDescriptor = frontendServiceServiceDescriptor.Methods().ByName("Get")
)

// FrontendServiceClient is a client for the frontend.v1.FrontendService service.
type FrontendServiceClient interface {
	Put(context.Context, *connect.Request[v1.PutRequest]) (*connect.Response[v1.PutResponse], error)
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
}

// NewFrontendServiceClient constructs a client for the frontend.v1.FrontendService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFrontendServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FrontendServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &frontendServiceClient{
		put: connect.NewClient[v1.PutRequest, v1.PutResponse](
			httpClient,
			baseURL+FrontendServicePutProcedure,
			connect.WithSchema(frontendServicePutMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.GetRequest, v1.GetResponse](
			httpClient,
			baseURL+FrontendServiceGetProcedure,
			connect.WithSchema(frontendServiceGetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// frontendServiceClient implements FrontendServiceClient.
type frontendServiceClient struct {
	put *connect.Client[v1.PutRequest, v1.PutResponse]
	get *connect.Client[v1.GetRequest, v1.GetResponse]
}

// Put calls frontend.v1.FrontendService.Put.
func (c *frontendServiceClient) Put(ctx context.Context, req *connect.Request[v1.PutRequest]) (*connect.Response[v1.PutResponse], error) {
	return c.put.CallUnary(ctx, req)
}

// Get calls frontend.v1.FrontendService.Get.
func (c *frontendServiceClient) Get(ctx context.Context, req *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// FrontendServiceHandler is an implementation of the frontend.v1.FrontendService service.
type FrontendServiceHandler interface {
	Put(context.Context, *connect.Request[v1.PutRequest]) (*connect.Response[v1.PutResponse], error)
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
}

// NewFrontendServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFrontendServiceHandler(svc FrontendServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	frontendServicePutHandler := connect.NewUnaryHandler(
		FrontendServicePutProcedure,
		svc.Put,
		connect.WithSchema(frontendServicePutMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	frontendServiceGetHandler := connect.NewUnaryHandler(
		FrontendServiceGetProcedure,
		svc.Get,
		connect.WithSchema(frontendServiceGetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/frontend.v1.FrontendService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FrontendServicePutProcedure:
			frontendServicePutHandler.ServeHTTP(w, r)
		case FrontendServiceGetProcedure:
			frontendServiceGetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFrontendServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFrontendServiceHandler struct{}

func (UnimplementedFrontendServiceHandler) Put(context.Context, *connect.Request[v1.PutRequest]) (*connect.Response[v1.PutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("frontend.v1.FrontendService.Put is not implemented"))
}

func (UnimplementedFrontendServiceHandler) Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("frontend.v1.FrontendService.Get is not implemented"))
}
