name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 10 * * 1' # run "At 10:00 on Monday"

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          #go-version-file: 'go.mod'
          go-version: '1.24.0-rc.1' 
          cache: true

      - name: Go Format
        run: gofmt -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: Go Build
        run: go build ./...

      - name: Go Lint
        run: go tool golangci-lint run ./...

      - name: Go Test
        run: go test -v -count=1 -race -shuffle=on ./...

      - name: Go Benchmark
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x ./...

      - name: Go Vuln Check
        run: go tool govulncheck -test ./...

      - name: Go Deadcode
        run: if [ -n "`go tool deadcode ./...`" ]; then exit 1; fi
