name: proto

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  run:
    name: Proto
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check proto diff
        run: go tool buf generate proto && git diff --exit-code

      - name: Buf lint
        run: go tool buf lint proto

      - name: Buf breaking
        run: go tool buf breaking proto --against "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,subdir=proto"
